# Minimal example to run the movegroup analysis pipeline with grouping variables

# To run this example you need a dataset with an id column, a datetime column, 
# latitude and longitude columns, and columns that contain your grouping 
# variables.

# This example is for two grouping variables. Here we use the grouping variables
# 'Season', i.e. the four meteorological seasons with values autumn, spring, 
# summer, and winter, and 'T.Ph', i.e. the Tidal Phase with values H, M, L,
# which stand for high, mid, and low tide, respectively.

# This is a minimal example. Please familiarize yourself with the different 
# parameters in each function and change or add parameters accordingly.

# load movegroup
library(movegroup)

# load data
data("TracksCleaned")
# > head(TracksCleaned,3)
#   Shark            Datetime      Lat       Lon Sex T.Ph
# 1  C25A 2012-10-03 09:50:00 25.73793 -79.24606   M    M
# 2  C25A 2012-10-03 09:55:00 25.73694 -79.24573   M    L
# 3  C25A 2012-10-03 10:00:00 25.73720 -79.24615   M    H

# define your saving directory
mysavedir <- file.path("Your", "directory", "here")

# space use analysis
{
  bins <- unique(TracksCleaned[c("Sex", "T.Ph")])
  bins <- bins[order(bins$Sex, bins$T.Ph), ]
  t_start <- Sys.time()
  
  # calculate movement models and absolute UDs
  for (i in seq_len(nrow(bins))) {
    sx <- bins$Sex[i]
    tp <- bins$T.Ph[i]
    TracksCleaned_i <- TracksCleaned |> dplyr::filter(Sex == sx, T.Ph == tp)
    message("\nNow calculating dBBMM for sex ", sx, " during tidal phase ", tp)
    movegroup::movegroup(
      data = TracksCleaned_i, # subsetted dataset based on grouping variables
      model = "dbbmm", # model choice: either "dbbmm" or "dbgb"
      ID = "Shark", # name of the column containing the animal ID's
      Datetime = "Datetime", # name of the column containing the timestamps
      Lat = "Lat", # name of the column containing the latitude information
      Lon = "Lon", # name of the column containing the longitude information
      buffpct = 5,
      savedir = file.path(mysavedir, sx, tp)) # Save outputs to your savedir.
      # Saveloc used here is a user-specified file.path. se and tp are the 
      # unique values for the grouping variables and are needed if you want to 
      # save your outputs in the correct subdirectories automatically.
  }
  
  # scale individual-level UDs/rasters to group-level UDs/rasters
  for (i in seq_len(nrow(bins))) {
    sx <- bins$Sex[i]
    tp <- bins$T.Ph[i]
    message("\nNow scaling rasters for sex ", sx, " during tidal phase ", tp)
    movegroup::scaleraster(
      path = file.path(mysavedir, sx, tp), # Path to directory where the 
      # individual-level UDs are saved.
      pathsubsets = file.path(mysavedir), # Path to parent directory that 
      # contains all UDs across spatial groups or subsets
      crsloc = file.path(mysavedir, sx, tp)) # Location of saved CRS Rds file 
      # from movegroup.R
  }
  
  # plot group-level UD-rasters
  for (i in seq_len(nrow(bins))) {
    sx <- bins$Sex[i]
    tp <- bins$T.Ph[i]
    message("\nNow plotting UD for sex ", sx, " during tidal phase ", tp)
    movegroup::plotraster(
      x = file.path(mysavedir, sx, tp, "Scaled", 
                    "All_Rasters_Scaled_Weighted_UDScaled.asc"), # Path to 
      # scaled raster generated by movegroup and scaleraster
      crsloc = file.path(mysavedir, sx, tp), # Location of saved CRS Rds file 
      # from movegroup.R
      mapsource = "google", # Map source for ggmap::get_map()
      maptype = "satellite", # Map type for ggmap::get_map() param maptype.
      gmapsAPI = "your_api_key_here", # Enter your stadia 
      # API here, quoted character 
      # string. See Details for instructions
      expandfactor = 1.2, # Extents expansion factor for basemap
      # mapzoom = 4, # Highest number = zoomed in. Google: 3 (continent) - 21 
      # (building). stamen: 0-18.
      savedir = file.path(mysavedir, sx, tp, "Scaled")) # # Save outputs 
      # to your savedir. mysavedir used here is a user-specified file.path
  } 
  message("\033[1;32m\ndBBMM space-use analysis completed in ",
          round(difftime(Sys.time(), t_start, units = "mins"), 0), " minutes\033[0m")
  beep(8)
}